version: '3'

services:
  nginx:
    image: nginx
    hostname: "nginx"
    container_name: "nginx"
    ports:
      - "80:80"
  
  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data
    ports:
      - 8000:8000
      - 9000:9000


  service-discovery:
    image: halverneus/static-file-server:latest
    hostname: service-discovery
    container_name: service-discovery
    volumes:
     - service-discovery-volume:/web
    ports: 
      - 1000:8080/tcp
  
volumes:
  portainer_data:
  service-discovery-volume:


